window.RECOMMENDATIONS_PAGE_DATA = {
  sections: [
    {
      id: 'favorites',
      title: 'General Favorites',
      subtitle: 'A few dependable nearby defaults for groceries, errands, and an easy beach start.'
    },
    {
      id: 'dining',
      title: 'Food And Dining',
      subtitle: 'A short restaurant list for the meals guests ask about most: breakfast, a special dinner, and a sunset favorite.'
    },
    {
      id: 'lgbtq',
      title: 'LGBTQ+ Puerto Vallarta',
      subtitle: 'Zona Romantica is one of Puerto Vallarta\'s most welcoming and lively neighborhoods, with plenty to enjoy whether you are going out casually or making a full evening of it.'
    },
    {
      id: 'after-dark',
      title: 'Optional After Dark',
      subtitle: 'For guests who want to stay out later, these are a few optional anchors and nightlife-forward stops to keep in mind.'
    }
  ],
  recommendations: [
    {
      id: 'mercado-ollin',
      section: 'favorites',
      category: 'Groceries',
      badge: 'Groceries',
      badgeIcon: '🛒',
      title: 'Mercado Ollin',
      description: 'A polished grocery stop in Zona Romantica for produce, wine, essentials, and easy first-day shopping.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mercado+Ollin+Puerto+Vallarta',
      websiteUrl: 'https://mercadoollin.com/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 10
    },
    {
      id: 'plaza-caracol',
      section: 'favorites',
      category: 'Shopping',
      badge: 'Shopping',
      badgeIcon: '🏬',
      title: 'Plaza Caracol',
      description: 'A dependable mall for errands, pharmacy runs, services, and broader shopping needs.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Plaza+Caracol+Puerto+Vallarta',
      websiteUrl: 'https://www.plazacaracol.mx/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 20
    },
    {
      id: 'los-muertos-beach',
      section: 'favorites',
      category: 'Beach',
      badge: 'Beach',
      badgeIcon: '🏖️',
      title: 'Los Muertos Beach',
      description: 'The neighborhood beach and pier area. Walkable, lively, and an easy default for a casual beach outing.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Los+Muertos+Beach+Puerto+Vallarta',
      websiteUrl: 'https://visitpuertovallarta.com/things-to-do/beaches/los-muertos-beach',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 30
    },
    {
      id: 'la-chilaqueria',
      section: 'dining',
      category: 'Breakfast',
      badge: 'Breakfast',
      badgeIcon: '☕',
      title: 'La Chilaqueria',
      description: 'A standout chilaquiles-and-brunch stop that feels local, approachable, and reliably worth the short walk.',
      googleMapsUrl: 'https://www.google.com/maps/place/La+chilaqueria/@20.603508,-105.2398176,16z/data=!3m1!4b1!4m6!3m5!1s0x84214566e8f7a1c5:0x68caaa44fd69d13f!8m2!3d20.603503!4d-105.2372427!16s%2Fg%2F11nxsb3trj?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://www.tripadvisor.com/Restaurant_Review-g150793-d23563896-Reviews-La_Chilaqueria-Puerto_Vallarta.html',
      phone: null,
      featured: true,
      featuredLabel: 'Best Breakfast',
      active: true,
      sortOrder: 10
    },
    {
      id: 'icu',
      section: 'dining',
      category: 'Dinner',
      badge: 'Dinner',
      badgeIcon: '✨',
      title: 'ICU',
      description: 'Creative, polished, and ideal for a special night when the goal is a more elevated Puerto Vallarta dinner.',
      googleMapsUrl: 'https://www.google.com/maps/place/IC%C3%9A/@20.6019591,-105.2401377,16z/data=!4m6!3m5!1s0x8421459f2249fbb1:0xd4fcc39b910aa093!8m2!3d20.6027409!4d-105.2366316!16s%2Fg%2F11hbbndg60?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://www.tripadvisor.com/Restaurant_Review-g150793-d13346080-Reviews-Restaurante_ICU-Puerto_Vallarta.html',
      phone: null,
      featured: true,
      featuredLabel: 'Best Dinner',
      active: true,
      sortOrder: 20
    },
    {
      id: 'la-cappella',
      section: 'dining',
      category: 'Sunset',
      badge: 'Sunset',
      badgeIcon: '🌅',
      title: 'La Cappella',
      description: 'A romantic classic with strong views and special-occasion energy. Reservations are a good idea.',
      googleMapsUrl: 'https://www.google.com/maps/place/La+Cappella+Restaurante/@20.6037876,-105.2329005,16z/data=!4m6!3m5!1s0x8421454e5eb48f3d:0x5e698bcf65a2adb8!8m2!3d20.6078329!4d-105.2339494!16s%2Fg%2F11fzf9t_6h?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://bellviewhotelboutique.com/la-cappella-restaurant/',
      phone: null,
      featured: true,
      featuredLabel: 'Best Sunset',
      active: true,
      sortOrder: 30
    },
    {
      id: 'mantamar',
      section: 'lgbtq',
      category: 'Beach Club',
      badge: 'Beach Club',
      badgeIcon: '🌈',
      title: 'Mantamar',
      description: 'An adults-only beach club at the south end of Los Muertos Beach with music, cocktails, and a more social scene.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mantamar+Beach+Club+Puerto+Vallarta',
      websiteUrl: 'https://www.mantamarvallarta.com/en',
      phone: null,
      featured: true,
      featuredLabel: 'Best Beach Day',
      active: true,
      sortOrder: 10
    },
    {
      id: 'mr-flamingo',
      section: 'lgbtq',
      category: 'Nightlife',
      badge: 'Nightlife',
      badgeIcon: '🍹',
      title: 'Mr. Flamingo',
      description: 'One of the neighborhood\'s best-known corners for cocktails, music, and a lively mixed crowd.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mr.+Flamingo+Puerto+Vallarta',
      websiteUrl: 'https://vallartahub.com/en/bars-and-nightclubs/mr-flamingo/',
      phone: null,
      featured: true,
      featuredLabel: 'Best Nightlife',
      active: true,
      sortOrder: 20
    },
    {
      id: 'act2pv',
      section: 'lgbtq',
      category: 'Shows',
      badge: 'Shows',
      badgeIcon: '🎭',
      title: 'Act2PV',
      description: 'A go-to theater and cabaret venue for performance-forward evenings in the neighborhood.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Act2PV+Puerto+Vallarta',
      websiteUrl: 'https://act2pv.com/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 30
    },
    {
      id: 'the-palm-cabaret',
      section: 'lgbtq',
      category: 'Shows',
      badge: 'Shows',
      badgeIcon: '🎭',
      title: 'The Palm Cabaret And Bar',
      description: 'A polished seated venue for drag shows and other cabaret-style entertainment.',
      googleMapsUrl: 'https://www.google.com/maps/place/The+Palm+Cabaret+and+Bar/@20.6000715,-105.2388605,18z/data=!3m1!4b1!4m6!3m5!1s0x84215ab4ace633a3:0xe2206abf41dbb883!8m2!3d20.600069!4d-105.237573!16s%2Fg%2F11b6shm570?entry=ttu&g_ep=EgoyMDI2MDQwMS4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://thepalmcabaret.com/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 40
    },
    {
      id: 'lazaro-cardenas-area',
      section: 'after-dark',
      category: 'Area Anchor',
      badge: 'Area Anchor',
      badgeIcon: '🌙',
      title: 'Lazaro Cardenas Park',
      description: 'A clearer landmark for guests who want to start walking Olas Altas, Lazaro Cardenas, and the nearby nightlife blocks.',
      googleMapsUrl: 'https://www.google.com/maps/place/Lazaro+Cardenas+Park/@20.6029078,-105.2401554,17z/data=!4m6!3m5!1s0x8421450de42639fd:0x51e829976da3b96b!8m2!3d20.6029081!4d-105.2375805!16s%2Fg%2F11g10h9v49?entry=ttu&g_ep=EgoyMDI2MDQwMS4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: null,
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 10
    },
    {
      id: 'south-end-los-muertos',
      section: 'after-dark',
      category: 'Optional',
      badge: 'Optional',
      badgeIcon: '🔞',
      title: 'South End Of Los Muertos Beach',
      description: 'A useful anchor point for the beach-club and after-dark zone at the south end.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=South+end+of+Los+Muertos+Beach+Puerto+Vallarta',
      websiteUrl: 'https://visitpuertovallarta.com/things-to-do/beaches/los-muertos-beach',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 20
    },
    {
      id: 'cheeky-pool-club',
      section: 'after-dark',
      category: 'Optional',
      badge: 'Optional',
      badgeIcon: '🔞',
      title: 'Cheeky Pool Club',
      description: 'An adults-only pool club option for guests who want a more playful daytime social scene.',
      googleMapsUrl: 'https://google.com/maps/place/Cheeky+Pool+Club/@20.6030159,-105.2341841,19.33z/data=!4m6!3m5!1s0x842145f057a80219:0xc64c2c7c50c66264!8m2!3d20.6041907!4d-105.2301998!16s%2Fg%2F11yl4cl0mf?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://www.instagram.com/cheekypoolclub/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 30
    },
    {
      id: 'spartacus-sauna',
      section: 'after-dark',
      category: 'Optional',
      badge: 'Optional',
      badgeIcon: '🔞',
      title: 'Spartacus Sauna',
      description: 'An optional adults-only reference for guests already seeking that specific experience.',
      googleMapsUrl: 'https://www.google.com/maps/place/Club-Sauna+Spartacus/@20.6034193,-105.2387595,17z/data=!3m1!4b1!4m6!3m5!1s0x8421454c7b519f57:0xcc02e49430647701!8m2!3d20.6034143!4d-105.2361846!16s%2Fg%2F12cnpk6cy?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://www.spaspartacus.com/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 40
    },
    {
      id: 'wet-dreams',
      section: 'after-dark',
      category: 'Optional',
      badge: 'Optional',
      badgeIcon: '🔞',
      title: 'Wet Dreams',
      description: 'A louder, more nightlife-forward option for guests specifically looking for that style of late-night stop.',
      googleMapsUrl: 'https://www.google.com/maps/place/Wetdreams/@20.6040237,-105.2736393,13z/data=!3m1!5s0x8421454c50ec6115:0x58a6ceca12d7ce38!4m10!1m2!2m1!1swetdrams!3m6!1s0x8421454c50c0ff3b:0xb4d12a88061107f!8m2!3d20.6036949!4d-105.2347232!15sCgh3ZXRkcmFtc1oKIgh3ZXRkcmFtc5IBB2dheV9iYXLgAQA!16s%2Fg%2F1tl8l0bp?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://todovallarta.com/mexico/wet-dreams/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 50
    }
  ]
};
