window.RECOMMENDATIONS_PAGE_DATA = {
  sections: [
    {
      id: 'favorites',
      title: 'Favoritos Generales',
      subtitle: 'Algunos favoritos cercanos y muy prácticos para despensa, mandados y una salida fácil a la playa.'
    },
    {
      id: 'dining',
      title: 'Comida y Restaurantes',
      subtitle: 'Una lista corta de restaurantes para los momentos que más preguntan los huéspedes: desayuno, una cena especial y una opción ideal para el atardecer.'
    },
    {
      id: 'lgbtq',
      title: 'Puerto Vallarta LGBTQ+',
      subtitle: 'Zona Romántica es una de las zonas más acogedoras y animadas de Puerto Vallarta, con mucho por disfrutar ya sea para una salida casual o una noche completa.'
    },
    {
      id: 'after-dark',
      title: 'Opcional para Después',
      subtitle: 'Para huéspedes que quieran seguir la noche, aquí van algunos puntos de referencia opcionales y lugares más orientados a la vida nocturna.'
    }
  ],
  recommendations: [
    {
      id: 'mercado-ollin',
      section: 'favorites',
      category: 'Despensa',
      badge: 'Despensa',
      badgeIcon: '🛒',
      title: 'Mercado Ollin',
      description: 'Una tienda bien surtida en Zona Romántica para fruta, vino, básicos y compras fáciles del primer día.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mercado+Ollin+Puerto+Vallarta',
      websiteUrl: 'https://mercadoollin.com/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 10
    },
    {
      id: 'plaza-caracol',
      section: 'favorites',
      category: 'Compras',
      badge: 'Compras',
      badgeIcon: '🏬',
      title: 'Plaza Caracol',
      description: 'Un centro comercial confiable para mandados, farmacia, servicios y compras más amplias.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Plaza+Caracol+Puerto+Vallarta',
      websiteUrl: 'https://www.plazacaracol.mx/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 20
    },
    {
      id: 'los-muertos-beach',
      section: 'favorites',
      category: 'Playa',
      badge: 'Playa',
      badgeIcon: '🏖️',
      title: 'Los Muertos Beach',
      description: 'La playa y el muelle del vecindario. Caminable, animada y una opción fácil para una salida casual a la playa.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Los+Muertos+Beach+Puerto+Vallarta',
      websiteUrl: 'https://visitpuertovallarta.com/things-to-do/beaches/los-muertos-beach',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 30
    },
    {
      id: 'la-chilaqueria',
      section: 'dining',
      category: 'Desayuno',
      badge: 'Desayuno',
      badgeIcon: '☕',
      title: 'La Chilaqueria',
      description: 'Una gran opción para chilaquiles y brunch que se siente local, accesible y muy recomendable para empezar el día.',
      googleMapsUrl: 'https://www.google.com/maps/place/La+chilaqueria/@20.603508,-105.2398176,16z/data=!3m1!4b1!4m6!3m5!1s0x84214566e8f7a1c5:0x68caaa44fd69d13f!8m2!3d20.603503!4d-105.2372427!16s%2Fg%2F11nxsb3trj?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://www.tripadvisor.com/Restaurant_Review-g150793-d23563896-Reviews-La_Chilaqueria-Puerto_Vallarta.html',
      phone: null,
      featured: true,
      featuredLabel: 'Mejor Desayuno',
      active: true,
      sortOrder: 10
    },
    {
      id: 'icu',
      section: 'dining',
      category: 'Cena',
      badge: 'Cena',
      badgeIcon: '✨',
      title: 'ICU',
      description: 'Creativo, pulido e ideal para una noche especial cuando quieres una cena más elevada en Puerto Vallarta.',
      googleMapsUrl: 'https://www.google.com/maps/place/IC%C3%9A/@20.6019591,-105.2401377,16z/data=!4m6!3m5!1s0x8421459f2249fbb1:0xd4fcc39b910aa093!8m2!3d20.6027409!4d-105.2366316!16s%2Fg%2F11hbbndg60?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://www.tripadvisor.com/Restaurant_Review-g150793-d13346080-Reviews-Restaurante_ICU-Puerto_Vallarta.html',
      phone: null,
      featured: true,
      featuredLabel: 'Mejor Cena',
      active: true,
      sortOrder: 20
    },
    {
      id: 'la-cappella',
      section: 'dining',
      category: 'Atardecer',
      badge: 'Atardecer',
      badgeIcon: '🌅',
      title: 'La Cappella',
      description: 'Un clásico romántico con grandes vistas y ambiente de ocasión especial. Conviene reservar.',
      googleMapsUrl: 'https://www.google.com/maps/place/La+Cappella+Restaurante/@20.6037876,-105.2329005,16z/data=!4m6!3m5!1s0x8421454e5eb48f3d:0x5e698bcf65a2adb8!8m2!3d20.6078329!4d-105.2339494!16s%2Fg%2F11fzf9t_6h?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://bellviewhotelboutique.com/la-cappella-restaurant/',
      phone: null,
      featured: true,
      featuredLabel: 'Mejor Atardecer',
      active: true,
      sortOrder: 30
    },
    {
      id: 'mantamar',
      section: 'lgbtq',
      category: 'Club de Playa',
      badge: 'Club de Playa',
      badgeIcon: '🌈',
      title: 'Mantamar',
      description: 'Un club de playa solo para adultos al sur de Los Muertos Beach, con música, cocteles y un ambiente más social.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mantamar+Beach+Club+Puerto+Vallarta',
      websiteUrl: 'https://www.mantamarvallarta.com/en',
      phone: null,
      featured: true,
      featuredLabel: 'Mejor Día de Playa',
      active: true,
      sortOrder: 10
    },
    {
      id: 'mr-flamingo',
      section: 'lgbtq',
      category: 'Vida nocturna',
      badge: 'Vida nocturna',
      badgeIcon: '🍹',
      title: 'Mr. Flamingo',
      description: 'Uno de los puntos más conocidos del vecindario para cocteles, música y un ambiente animado y diverso.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mr.+Flamingo+Puerto+Vallarta',
      websiteUrl: 'https://vallartahub.com/en/bars-and-nightclubs/mr-flamingo/',
      phone: null,
      featured: true,
      featuredLabel: 'Mejor Vida Nocturna',
      active: true,
      sortOrder: 20
    },
    {
      id: 'act2pv',
      section: 'lgbtq',
      category: 'Shows',
      badge: 'Shows',
      badgeIcon: '🎭',
      title: 'Act2PV',
      description: 'Un teatro y cabaret de referencia para noches centradas en espectáculos en el vecindario.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Act2PV+Puerto+Vallarta',
      websiteUrl: 'https://act2pv.com/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 30
    },
    {
      id: 'the-palm-cabaret',
      section: 'lgbtq',
      category: 'Shows',
      badge: 'Shows',
      badgeIcon: '🎭',
      title: 'The Palm Cabaret And Bar',
      description: 'Un venue cómodo y pulido para drag shows y otro entretenimiento tipo cabaret.',
      googleMapsUrl: 'https://www.google.com/maps/place/The+Palm+Cabaret+and+Bar/@20.6000715,-105.2388605,18z/data=!3m1!4b1!4m6!3m5!1s0x84215ab4ace633a3:0xe2206abf41dbb883!8m2!3d20.600069!4d-105.237573!16s%2Fg%2F11b6shm570?entry=ttu&g_ep=EgoyMDI2MDQwMS4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://thepalmcabaret.com/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 40
    },
    {
      id: 'lazaro-cardenas-area',
      section: 'after-dark',
      category: 'Punto de referencia',
      badge: 'Punto de referencia',
      badgeIcon: '🌙',
      title: 'Lazaro Cardenas Park',
      description: 'Un punto claro de referencia para empezar a caminar por Olas Altas, Lázaro Cárdenas y las cuadras de vida nocturna cercanas.',
      googleMapsUrl: 'https://www.google.com/maps/place/Lazaro+Cardenas+Park/@20.6029078,-105.2401554,17z/data=!4m6!3m5!1s0x8421450de42639fd:0x51e829976da3b96b!8m2!3d20.6029081!4d-105.2375805!16s%2Fg%2F11g10h9v49?entry=ttu&g_ep=EgoyMDI2MDQwMS4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: null,
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 10
    },
    {
      id: 'south-end-los-muertos',
      section: 'after-dark',
      category: 'Opcional',
      badge: 'Opcional',
      badgeIcon: '🔞',
      title: 'South End Of Los Muertos Beach',
      description: 'Un punto útil de referencia para la zona de beach clubs y vida nocturna al extremo sur.',
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=South+end+of+Los+Muertos+Beach+Puerto+Vallarta',
      websiteUrl: 'https://visitpuertovallarta.com/things-to-do/beaches/los-muertos-beach',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 20
    },
    {
      id: 'cheeky-pool-club',
      section: 'after-dark',
      category: 'Opcional',
      badge: 'Opcional',
      badgeIcon: '🔞',
      title: 'Cheeky Pool Club',
      description: 'Una opción solo para adultos para huéspedes que buscan una escena social más juguetona durante el día.',
      googleMapsUrl: 'https://google.com/maps/place/Cheeky+Pool+Club/@20.6030159,-105.2341841,19.33z/data=!4m6!3m5!1s0x842145f057a80219:0xc64c2c7c50c66264!8m2!3d20.6041907!4d-105.2301998!16s%2Fg%2F11yl4cl0mf?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://www.instagram.com/cheekypoolclub/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 30
    },
    {
      id: 'spartacus-sauna',
      section: 'after-dark',
      category: 'Opcional',
      badge: 'Opcional',
      badgeIcon: '🔞',
      title: 'Spartacus Sauna',
      description: 'Una referencia opcional solo para adultos para huéspedes que ya buscan exactamente esa experiencia.',
      googleMapsUrl: 'https://www.google.com/maps/place/Club-Sauna+Spartacus/@20.6034193,-105.2387595,17z/data=!3m1!4b1!4m6!3m5!1s0x8421454c7b519f57:0xcc02e49430647701!8m2!3d20.6034143!4d-105.2361846!16s%2Fg%2F12cnpk6cy?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://www.spaspartacus.com/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 40
    },
    {
      id: 'wet-dreams',
      section: 'after-dark',
      category: 'Opcional',
      badge: 'Opcional',
      badgeIcon: '🔞',
      title: 'Wet Dreams',
      description: 'Una opción más ruidosa y muy orientada a la vida nocturna para huéspedes que buscan específicamente ese estilo de salida nocturna.',
      googleMapsUrl: 'https://www.google.com/maps/place/Wetdreams/@20.6040237,-105.2736393,13z/data=!3m1!5s0x8421454c50ec6115:0x58a6ceca12d7ce38!4m10!1m2!2m1!1swetdrams!3m6!1s0x8421454c50c0ff3b:0xb4d12a88061107f!8m2!3d20.6036949!4d-105.2347232!15sCgh3ZXRkcmFtc1oKIgh3ZXRkcmFtc5IBB2dheV9iYXLgAQA!16s%2Fg%2F1tl8l0bp?entry=ttu&g_ep=EgoyMDI2MDExMy4wIKXMDSoASAFQAw%3D%3D',
      websiteUrl: 'https://todovallarta.com/mexico/wet-dreams/',
      phone: null,
      featured: false,
      featuredLabel: null,
      active: true,
      sortOrder: 50
    }
  ]
};
